services:
    psql:
        image: postgres
        ports:
            - 5431:5432
        volumes:
            - hypertube-data:/var/lib/psql
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: hypertube
    api:
        image: hypertube-api
        restart: always
        ports:
            - 3000:3000
        environment:
            HYPERTUBE_ENV: production
        depends_on:
            - psql
    media:
        image: hypertube-media
        restart: always
        ports:
            - 8080:8080
        environment:
            HYPERTUBE_ENV: production

volumes:
    hypertube-data:
