services:
    psql:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - psql:/var/lib/psql
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: hypertube
    api:
        image: hypertube-api
        restart: unless-stopped
        ports:
            - 3000:3000
        environment:
            HYPERTUBE_ENV: production
        depends_on:
            - psql
    media:
        image: hypertube-media
        restart: unless-stopped
        expose: # expose port to internal services only
            - 8080
        environment:
            HYPERTUBE_ENV: production
    jackett:
        image: ghcr.io/linuxserver/jackett
        restart: unless-stopped
        env_file:
            - ./.config/docker/compose/.env
        ports:
            - 9117:9117
        volumes:
            - /config/jackett/config:/config
volumes:
    psql:
