services:
    web-server:
        build: ./
        restart: always
        ports:
            - 3000:8080
        volumes:
            - ./:/app
    psql:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: docker
        volumes:
            - hypertube-data:/var/lib/sql

volumes:
    hypertube-data:
