version: '3'

services:
    reverse:
        image: jonasal/nginx-certbot:latest
        container_name: reverse_proxy
        restart: unless-stopped
        env_file:
          - ./nginx-certbot.env
        ports:
          - 80:80
          - 443:443
        volumes:
          - nginx_secrets:/etc/letsencrypt
          - ./user_conf.d:/etc/nginx/user_conf.d
    client:
        image: mrta/vuejs-client
        container_name: client
        ports:
            - 80:80
    psql:
        image: postgres
        container_name: psql
        volumes:
            - psql:/var/lib/psql
        env_file:
            - ../../.env.development.local
        ports:
            - 5432:5432
    api:
        image: mrta/hypertube-api
        container_name: api
        ports:
            - 3000:3000
        restart: unless-stopped
        env_file:
            - ../../.env.development.local
        depends_on:
            - psql
    media:
        image: mrta/hypertube-media
        container_name: media
        ports:
            - 8080:8080
        restart: unless-stopped
        env_file:
            - ../../.env.development.local
    transcoder:
        image: mrta/hypertube-transcoder
        container_name: transcoder
        ports:
            - 3010:3010
        restart: unless-stopped
        env_file:
            - ../../.env.development.local
        deploy:
            resources:
                limits:
                    cpus: 1
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        ports:
            - 9117:9117
        restart: unless-stopped
        env_file:
            - ../../.env.development.local
        volumes:
            - /config/jackett/config:/config
volumes:
    psql:
    nginx_secrets:
